package pgtest

import (
	"database/sql"
	"testing"
)

// A database goes back to the pool empty, its sequences restarted, its
// schema kept, any session a test left open ended; one whose schema a test
// changed is dropped instead.
func TestPool(t *testing.T) {
	if !Enabled() {
		t.Skip("Postgres only (" + Env + ")")
	}
	var first string
	var leftOpen *sql.DB
	t.Run("write", func(t *testing.T) {
		first = NewDB(t)
		db := open(t, first)
		exec(t, db, `CREATE TABLE a (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v text NOT NULL)`,
			`CREATE TABLE b (a bigint NOT NULL REFERENCES a)`,
			`INSERT INTO a (v) VALUES ('x'), ('y')`, `INSERT INTO b VALUES (2)`)
		leftOpen = db // never closed: emptying ends its session
	})
	defer leftOpen.Close()
	t.Run("reuse", func(t *testing.T) {
		if got := NewDB(t); got != first {
			t.Fatalf("got %s, want the pool's %s", got, first)
		}
		db := open(t, first)
		defer db.Close()
		var n int
		if err := db.QueryRow(`SELECT (SELECT count(*) FROM a) + (SELECT count(*) FROM b)`).Scan(&n); err != nil || n != 0 {
			t.Fatalf("rows left: %d, %v", n, err)
		}
		var id int64
		if err := db.QueryRow(`INSERT INTO a (v) VALUES ('z') RETURNING id`).Scan(&id); err != nil || id != 1 {
			t.Fatalf("next id %d, %v; want 1", id, err)
		}
		exec(t, db, `ALTER TABLE a ALTER COLUMN v DROP NOT NULL`)
	})
	t.Run("changed schema", func(t *testing.T) {
		if got := NewDB(t); got == first {
			t.Fatal("a database whose schema a test changed was reused")
		}
	})
}

func open(t *testing.T, url string) *sql.DB {
	t.Helper()
	db, err := sql.Open("pgx", url)
	if err != nil {
		t.Fatal(err)
	}
	return db
}

func exec(t *testing.T, db *sql.DB, stmts ...string) {
	t.Helper()
	for _, s := range stmts {
		if _, err := db.Exec(s); err != nil {
			t.Fatalf("%s: %v", s, err)
		}
	}
}
