package core

import (
	"context"
	"database/sql"
	"fmt"
	"runtime"

	_ "github.com/jackc/pgx/v5/stdlib"
)

// schemaPG is the layout of schemaSQL on Postgres (Addendum D.8). The
// tables, columns and constraints are the same, so every query runs on
// both; the types differ:
//
//   - integer keys are bigint identities, flags and small codes smallint
//     (not boolean: queries compare them with 0 and 1 on both dialects);
//   - hashes are bytea, checked to be 20 bytes;
//   - canonical JSON is text, never jsonb, which would reorder keys and
//     normalise numbers: ids are served and re-hashed from exactly the
//     stored bytes (§3.1). The columns that hold an encrypted row when
//     encryption at rest is on (crypt.go: revisions.patches, heads.doc,
//     snapshots.doc, grants.blocks) are bytea, which keeps the plaintext's
//     bytes just as exactly;
//   - timestamps stay integer Unix milliseconds, as in SQLite.
//
// Patch sets stay in revisions, as in the SQLite layout, rather than in a
// table of their own (D.8 "content apart from the skeleton"): purge and
// pruning set them to NULL, and vacuum reclaims the space.
const schemaPG = `
CREATE TABLE IF NOT EXISTS namespaces (
  ns         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text     NOT NULL UNIQUE,
  base       bigint   REFERENCES namespaces,
  base_at    bigint,
  base_config_seq bigint,
  frozen     smallint NOT NULL DEFAULT 0,
  purged     smallint NOT NULL DEFAULT 0,
  head_seq   bigint,
  config_seq bigint
);
CREATE TABLE IF NOT EXISTS authors (author bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS resources (
  res         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ns          bigint   NOT NULL REFERENCES namespaces,
  name        text     NOT NULL,
  head_seq    bigint,
  state       smallint NOT NULL DEFAULT 0,
  horizon_seq bigint,
  keep        text,
  UNIQUE (ns, name)
);

CREATE TABLE IF NOT EXISTS revisions (
  seq        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  res        bigint   NOT NULL REFERENCES resources,
  id         bytea    NOT NULL CHECK (octet_length(id) = 20),
  parent_seq bigint,
  first      smallint NOT NULL DEFAULT 0,
  kind       smallint NOT NULL,
  patches    bytea,
  author     bigint   NOT NULL REFERENCES authors,
  via        text,
  grant_id   bytea,
  signature  text,
  schema_ref text,
  created    bigint   NOT NULL,
  UNIQUE (res, id),
  UNIQUE (res, parent_seq)
);
CREATE UNIQUE INDEX IF NOT EXISTS one_first ON revisions (res) WHERE first = 1;
-- Databases from before v0.33 named it revisions_id.
DO $$ BEGIN
  IF to_regclass('revisions_id') IS NOT NULL THEN
    IF to_regclass('revisions_by_id') IS NULL THEN ALTER INDEX revisions_id RENAME TO revisions_by_id;
    ELSE DROP INDEX revisions_id;
    END IF;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS revisions_by_id ON revisions (id);  -- also finds draft schema revisions in branches (§6.1, D.2)
CREATE INDEX IF NOT EXISTS revisions_res_seq ON revisions (res, seq);

CREATE TABLE IF NOT EXISTS grants (id bytea PRIMARY KEY, blocks bytea NOT NULL);

CREATE TABLE IF NOT EXISTS deks (
  res        bigint PRIMARY KEY,
  wrapped    bytea  NOT NULL,
  keystore   text   NOT NULL,
  created    bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS epoch_keys (
  ns         bigint NOT NULL REFERENCES namespaces,
  epoch      bigint NOT NULL,
  wrapped    bytea  NOT NULL,
  keystore   text   NOT NULL,
  created    bigint NOT NULL,
  PRIMARY KEY (ns, epoch)
);
CREATE TABLE IF NOT EXISTS rev_epochs (seq bigint PRIMARY KEY, epoch bigint NOT NULL);
CREATE TABLE IF NOT EXISTS sealed (
  ns         bigint NOT NULL,
  kind       text   NOT NULL,
  key        text   NOT NULL,
  name       text,
  rev_seq    bigint,
  jwe        text   NOT NULL,
  created    bigint NOT NULL,
  PRIMARY KEY (ns, kind, key)
);
CREATE INDEX IF NOT EXISTS sealed_name ON sealed (ns, name);
CREATE INDEX IF NOT EXISTS sealed_rev ON sealed (rev_seq);

CREATE TABLE IF NOT EXISTS e2e_epochs (
  ns         bigint NOT NULL REFERENCES namespaces,
  epoch      bigint NOT NULL,
  created    bigint NOT NULL,
  PRIMARY KEY (ns, epoch)
);
CREATE TABLE IF NOT EXISTS e2e_snapshots (seq bigint PRIMARY KEY REFERENCES revisions, res bigint NOT NULL, jwe text NOT NULL);
CREATE INDEX IF NOT EXISTS e2e_snapshots_res ON e2e_snapshots (res, seq);

CREATE TABLE IF NOT EXISTS heads (res bigint PRIMARY KEY REFERENCES resources, seq bigint NOT NULL, doc bytea NOT NULL) WITH (fillfactor = 70);
CREATE INDEX IF NOT EXISTS heads_seq ON heads (seq);
CREATE TABLE IF NOT EXISTS snapshots (seq bigint PRIMARY KEY REFERENCES revisions, res bigint NOT NULL, doc bytea NOT NULL);
CREATE INDEX IF NOT EXISTS snapshots_res ON snapshots (res, seq);

CREATE TABLE IF NOT EXISTS archives (
  seq        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  res        bigint NOT NULL REFERENCES resources,
  from_seq   bigint NOT NULL,
  to_seq     bigint NOT NULL,
  key        text   NOT NULL,
  url        text   NOT NULL,
  created    bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS archives_res ON archives (res, from_seq);

CREATE TABLE IF NOT EXISTS ns_log (
  seq        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ns         bigint   NOT NULL REFERENCES namespaces,
  id         bytea    NOT NULL CHECK (octet_length(id) = 20),
  prev_seq   bigint,
  kind       smallint NOT NULL,
  res        bigint,
  target_seq bigint,
  body       text     NOT NULL,
  config_seq bigint   NOT NULL,
  author     bigint   NOT NULL REFERENCES authors,
  created    bigint   NOT NULL,
  kid        text,
  UNIQUE (ns, id),
  UNIQUE (ns, prev_seq)
);
CREATE UNIQUE INDEX IF NOT EXISTS one_ns_first ON ns_log (ns) WHERE prev_seq IS NULL;

CREATE TABLE IF NOT EXISTS head_history (
  res        bigint NOT NULL REFERENCES resources,
  ns_seq     bigint NOT NULL REFERENCES ns_log,
  target_seq bigint NOT NULL REFERENCES revisions,
  PRIMARY KEY (res, ns_seq)
);

CREATE TABLE IF NOT EXISTS ns_config (
  seq        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ns         bigint NOT NULL REFERENCES namespaces,
  id         bytea  NOT NULL CHECK (octet_length(id) = 20),
  parent_seq bigint,
  patches    text   NOT NULL,
  doc        text   NOT NULL,
  author     bigint NOT NULL REFERENCES authors,
  created    bigint NOT NULL,
  UNIQUE (ns, id),
  UNIQUE (ns, parent_seq)
);
CREATE UNIQUE INDEX IF NOT EXISTS one_config_genesis ON ns_config (ns) WHERE parent_seq IS NULL;

CREATE TABLE IF NOT EXISTS blobs (
  res      bigint   NOT NULL REFERENCES resources,
  bid      bytea    NOT NULL CHECK (octet_length(bid) = 20),
  type     text     NOT NULL,
  nonce    text,
  size     bigint   NOT NULL,
  hash     bytea    NOT NULL,
  owner    bigint   NOT NULL,
  created  bigint   NOT NULL,
  ref_seq  bigint   NOT NULL REFERENCES revisions,
  pruned   smallint NOT NULL DEFAULT 0,
  PRIMARY KEY (res, bid)
);
CREATE INDEX IF NOT EXISTS blobs_bytes ON blobs (owner, hash);
CREATE TABLE IF NOT EXISTS blob_pending (
  res      bigint NOT NULL REFERENCES resources,
  bid      bytea  NOT NULL CHECK (octet_length(bid) = 20),
  uploader text   NOT NULL,
  type     text   NOT NULL,
  nonce    text,
  size     bigint NOT NULL,
  hash     bytea  NOT NULL,
  owner    bigint NOT NULL,
  created  bigint NOT NULL,
  PRIMARY KEY (res, bid, uploader)
);
CREATE INDEX IF NOT EXISTS blob_pending_bytes ON blob_pending (owner, hash);
CREATE INDEX IF NOT EXISTS blob_pending_created ON blob_pending (created);
-- One row per namespace and uploader, locked by each upload before it sums
-- the uploader's pending bytes (§7.8): uploads hold the namespace's lock
-- only shared (D.8), so this row orders an uploader's own uploads.
CREATE TABLE IF NOT EXISTS blob_uploaders (
  ns       bigint NOT NULL,
  uploader text   NOT NULL,
  PRIMARY KEY (ns, uploader)
);
CREATE TABLE IF NOT EXISTS blob_refs (
  res      bigint NOT NULL REFERENCES resources,
  bid      bytea  NOT NULL,
  from_seq bigint NOT NULL,
  to_seq   bigint,
  PRIMARY KEY (res, bid, from_seq)
);
-- Blob bytes in files under the blob directory every instance shares (file),
-- or without one as bytea (blobstore.go). Values are at most blobSize, far
-- below bytea's 1 GB.
CREATE TABLE IF NOT EXISTS blob_bytes (
  owner    bigint NOT NULL,
  hash     bytea  NOT NULL,
  data     bytea  NOT NULL,
  file     text,
  UNIQUE (owner, hash)
);
CREATE TABLE IF NOT EXISTS blob_epochs (
  ns       bigint NOT NULL,
  name     text   NOT NULL,
  bid      bytea  NOT NULL CHECK (octet_length(bid) = 20),
  epoch    bigint NOT NULL,
  data     bytea,
  file     text,
  created  bigint NOT NULL,
  PRIMARY KEY (ns, name, bid, epoch)
);

CREATE TABLE IF NOT EXISTS cdn_repurge (
  id       bigserial PRIMARY KEY,
  ns_seq   bigint UNIQUE,
  tags     text   NOT NULL,
  due      bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS cdn_repurge_due ON cdn_repurge (due);

CREATE TABLE IF NOT EXISTS remote_branches (
  ns         bigint NOT NULL REFERENCES namespaces,
  origin     text   NOT NULL,
  name       text   NOT NULL,
  at_seq     bigint NOT NULL,
  ns_seq     bigint NOT NULL,
  prev_seq   bigint,
  expires    bigint NOT NULL,
  PRIMARY KEY (ns, origin, name)
);

CREATE TABLE IF NOT EXISTS remote_bases (
  shadow      bigint PRIMARY KEY REFERENCES namespaces,
  branch      bigint NOT NULL UNIQUE REFERENCES namespaces,
  origin      text   NOT NULL,
  ns          text   NOT NULL,
  at          text   NOT NULL,
  checkpoint  text   NOT NULL,
  reg_ns_id   text,
  reg_expires bigint
);

CREATE TABLE IF NOT EXISTS remote_notices (
  seq       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch    bigint   NOT NULL REFERENCES namespaces,
  id        text     NOT NULL,
  kind      text     NOT NULL,
  resource  text,
  applied   smallint NOT NULL,
  created   bigint   NOT NULL,
  UNIQUE (branch, id)
);

-- The tailer (tailer.go) follows ns_log by transaction id, and reads
-- cache_gen, which commits that change what reads may return increment.
ALTER TABLE ns_log ADD COLUMN IF NOT EXISTS xid xid8 NOT NULL DEFAULT pg_current_xact_id();
CREATE INDEX IF NOT EXISTS ns_log_xid ON ns_log (xid);
-- Blob files (blobstore.go).
ALTER TABLE blob_bytes ADD COLUMN IF NOT EXISTS file text;
ALTER TABLE blob_epochs ADD COLUMN IF NOT EXISTS file text;
-- The id of namespaces.head_seq, read with the row's lock (appendNS); NULL
-- in rows from before it and in remote shadows, whose ids are looked up.
ALTER TABLE namespaces ADD COLUMN IF NOT EXISTS head_id bytea;
-- Revisions, and their stored patch sets' bytes, since a resource's last
-- intermediate snapshot (insertItems); NULL: count them.
ALTER TABLE resources ADD COLUMN IF NOT EXISTS snap_revs bigint;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS snap_bytes bigint;
CREATE TABLE IF NOT EXISTS cache_gen (id smallint PRIMARY KEY CHECK (id = 1), gen bigint NOT NULL);
INSERT INTO cache_gen (id, gen) VALUES (1, 0) ON CONFLICT DO NOTHING;
`

// openPG opens a Postgres database and creates or migrates its schema.
func openPG(url string) (*sql.DB, error) {
	db, err := sql.Open("pgx", url)
	if err != nil {
		return nil, err
	}
	n := 4 * runtime.GOMAXPROCS(0)
	db.SetMaxOpenConns(n)
	db.SetMaxIdleConns(n)
	if err := migratePG(db); err != nil {
		db.Close()
		return nil, err
	}
	return db, nil
}

// migratePG creates the schema, or migrates one created by an earlier
// version, in one transaction under an advisory lock, so instances
// starting together don't race.
func migratePG(db *sql.DB) error {
	ctx := context.Background()
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.ExecContext(ctx, `SELECT pg_advisory_xact_lock($1, $2)`, lockClass, lockSchema); err != nil {
		return err
	}
	if _, err := tx.ExecContext(ctx, schemaPG); err != nil {
		return fmt.Errorf("creating schema: %w", err)
	}
	return tx.Commit()
}
